version: '3'

services:
  selenoid:
    image: "aerokube/selenoid:1.10.1"
    network_mode: bridge
    restart: always
    environment:
      TZ: "Europe/Kiev"
    ports:
      - "4444:4444"
    volumes:
      - "$PWD/etc/selenoid:/etc/selenoid/"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: ["-conf", "/etc/selenoid/browsers.json", "-limit", "2"]

  selenoid-ui:
    image: "aerokube/selenoid-ui:1.10.3"
    network_mode: bridge
    restart: always
    depends_on:
      - selenoid
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]